export const theme = {
  primaryColor: '#fff',
  secondaryColor: '#48dbfb',
  cardColor: '#121212',
  backgroundColor: '#030303',
  textPrimary: '#e0206c',
  textSecondary: '#878587',
  textLight: '#b6b6b8',
  breakpointLg: '920px',
  maxWidth: '1800px',
  primaryFont: `'Titillium Web', sans-serif`,
  secondaryFont: `'Rock Salt', cursive`,
  breakpoints: {
    fold: 'screen and (max-width:280px)',
    iphone: 'screen and (max-width:320px)',
    mobile: 'screen and (max-width:375px)',
    xsm: 'screen and (max-width:414px)',
    sm: 'screen and (max-width:640px)',
    md: 'screen and (max-width:768px)',
    minMd: 'screen and (min-width:769px)',
    lg: 'screen and (max-width:1024px)',
    xl: 'screen and (max-width:1280px)',
    height: 'screen and (min-height:1200px)',
  },
};
